In [89]:
import numpy as np

print(np.__version__)


2.4.2


In [90]:
arr = np.array([1,2,3,4,5])
print(arr)
print(arr.ndim)
print(type(arr))
print(arr.dtype)

[1 2 3 4 5]
1
<class 'numpy.ndarray'>
int64


In [91]:
a1= np.array([[1,2,3],[4,5,6]])
print(a1)
print(a1.ndim)
print(a1.shape)
print(a1.size)

[[1 2 3]
 [4 5 6]]
2
(2, 3)
6


In [92]:
a2= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a2)
print(a2.ndim)
print(a2.shape)
print(a2.size)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3
(2, 2, 3)
12


In [93]:
print(np.zeros((4,4)))
print(np.ones((3,3)))
print(np.full((4,4), 5))
print(np.eye(3))
print(np.arange(0,10,1))
print(np.linspace(0,10,10))
print(np.random.rand(3,3))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 1 2 3 4 5 6 7 8 9]
[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
[[0.26619752 0.53967649 0.55849342]
 [0.78592941 0.17801243 0.17914831]
 [0.02358533 0.94633888 0.4412273 ]]


In [94]:
arr=np.arange(4)
reshaped = arr.reshape(2,2)
print(reshaped)

[[0 1]
 [2 3]]


In [95]:
arr3= np.array([1,2,3,4,5])
print(arr3[0::])
print(arr3[2])


[1 2 3 4 5]
3


In [100]:
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])
print(matrix[1:,1:3])

[[5 6]
 [8 9]]
